config:
  version-candidate: 123123dsfdsfdsfsdf
build:
  quality:
      test-job:
        machine: graknlabs-ubuntu-20.04
        script: |
          echo 123
release:
  validation:
    job:
      machine: graknlabs-ubuntu-20.04
      script: |
        echo Released!
