build:

  performance:
    test-performance-small-grakn-background:
      machine: graknlabs-ubuntu-20.04-java11
      type: background
      timeout: "18000"
      script: |
        cat > grakn.service <<- EOM
        [Unit]
        Description=Grakn Core

        [Service]
        Type=simple
        ExecStart=/home/grabl/simulation/dist/grakn-core-all-linux/grakn server --no-grabl-trace --grabl-uri=$GRABL_TRACING_URI --grabl-username=$GRABL_OWNER --grabl-token=$GRABL_TOKEN
        Restart=on-failure
        RestartSec=10
        KillMode=process

        [Install]
        WantedBy=multi-user.target
        EOM

        sudo mv grakn.service /etc/systemd/system/

        bazel run //test:grakn-extractor-linux -- dist/grakn-core-all-linux
        cd ./dist/grakn-core-all-linux/

        sudo systemctl daemon-reload
        sudo systemctl start grakn
        export GRABL_EXPORT_PERFORMANCE_SMALL_GRAKN_URI="${HOSTNAME}:1729"
    test-performance-small-grakn:
      machine: graknlabs-ubuntu-20.04-java11
      timeout: "18000"
      dependencies: [test-performance-small-grakn-background]
      script: |
        bazel run //:simulation-small -- \
          --database grakn \
          --database-uri $GRABL_EXPORT_PERFORMANCE_SMALL_GRAKN_URI \
          --tracing-uri $GRABL_TRACING_URI \
          --org $GRABL_OWNER \
          --repo $GRABL_REPO \
          --commit $GRABL_COMMIT \
          --username $GRABL_OWNER \
          --api-token $GRABL_TOKEN \
          --config-file /home/grabl/$GRABL_REPO/config/config_small.yml