build:
  performance:
    test-performance-small-grakn-core-background:
      image: graknlabs-ubuntu-20.04
      type: background
      timeout: "30m"
      command: |
        wget "https://storage.googleapis.com/grabl-dev-secrets/rootCA.jks"
        cp rootCA.jks /tmp/rootCA.jks

        cat > grakn-core.service <<- EOM
        [Unit]
        Description=Grakn Core

        [Service]
        Type=simple
        Environment="SERVER_JAVAOPTS=-Xmx16G -Djavax.net.ssl.trustStore=/tmp/rootCA.jks -Djavax.net.ssl.trustStorePassword=changeit"
        ExecStart=/home/grabl/$GRABL_REPO/dist/grakn-core-all-linux/grakn server
        Restart=on-failure
        RestartSec=10
        KillMode=process


        [Install]
        WantedBy=multi-user.target
        EOM

        sudo mv grakn-core.service /etc/systemd/system/

        bazel run //test:grakn-core-extractor-linux -- dist/grakn-core-all-linux
        cd ./dist/grakn-core-all-linux/

        sudo systemctl daemon-reload
        sudo systemctl start grakn-core
        export GRABL_EXPORT_PERFORMANCE_SMALL_GRAKN_CORE_URI="${HOSTNAME}:1729"
      monitor: |
        sleep 10s
        tail -f -n +1 /home/grabl/$GRABL_REPO/dist/grakn-core-all-linux/server/logs/grakn.log
    test-performance-small-grakn-core:
      image: graknlabs-ubuntu-20.04
      timeout: "30m"
      dependencies: [test-performance-small-grakn-core-background]
      command: |
        wget "https://storage.googleapis.com/grabl-dev-secrets/rootCA.jks"
        cp rootCA.jks /tmp/rootCA.jks

        bazel run --jvmopt="-Djavax.net.ssl.trustStore=/tmp/rootCA.jks -Djavax.net.ssl.trustStorePassword=changeit" //:benchmark-small -- \
          --database "Grakn Core 2.0" \
          --database-uri $GRABL_EXPORT_PERFORMANCE_SMALL_GRAKN_CORE_URI \
          --tracing-uri $GRABL_TRACING_URI \
          --org $GRABL_OWNER \
          --repo $GRABL_REPO \
          --commit $GRABL_COMMIT \
          --username $GRABL_OWNER \
          --api-token $GRABL_TOKEN \
          --config-file /home/grabl/$GRABL_REPO/config/config_test.yml