config:
  version-candidate: VERSION
build:
  quality:
      test-job:
        machine: graknlabs-ubuntu-20.04
        script: |
          echo "$i iterations complete"
release: 
  filter:
    owner: Phillammon
    branch: master
  validation:
    job:
      machine: graknlabs-ubuntu-20.04
      script: |
        echo Released!
  deployment:
    job:
      machine: graknlabs-ubuntu-20.04
      script: |
        echo Released!
