build:
  performance:
    test-performance-small-grakn-background:
      machine: graknlabs-ubuntu-20.04-long
      type: background
      timeout: "18000"
      script: |
        bazel run //test:grakn-extractor -- dist/grakn-core-all-linux
        cd ./dist/grakn-core-all-linux/
        SERVER_JAVAOPTS="-Djavax.net.ssl.trustStore=/tmp/rootCA.jks -Djavax.net.ssl.trustStorePassword=changeit" ./grakn server start -- \
          --tracing-uri $GRABL_TRACING_URI \
          --tracing-username $GRABL_OWNER \
          --tracing-access-token $GRABL_TOKEN
        export GRABL_EXPORT_PERFORMANCE_SMALL_GRAKN_URI="${HOSTNAME}:48555"
    test-performance-small-grakn:
      machine: graknlabs-ubuntu-20.04-long
      timeout: "18000"
      dependencies: [test-performance-small-grakn-background]
      script: |
        bazel run //:simulation-small -- \
          --database grakn \
          --database-uri $GRABL_EXPORT_PERFORMANCE_SMALL_GRAKN_URI \
          --tracing-uri $GRABL_TRACING_URI \
          --org $GRABL_OWNER \
          --repo $GRABL_REPO \
          --commit $GRABL_COMMIT \
          --username $GRABL_OWNER \
          --api-token $GRABL_TOKEN \
          --config-file /home/grabl/$GRABL_REPO/config/config_small.yml