#
# Copyright (C) 2020 Grakn Labs
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

config:
  version-candidate: VERSION

build:
  quality:
    filter:
      owner: graknlabs
      branch: main
    build-analysis:
      machine: graknlabs-ubuntu-20.04-java11
      script: |
        echo 1
  correctness:
    build:
      machine: graknlabs-ubuntu-20.04-java11
      script: |
        echo 2
    build-dependency:
      machine: graknlabs-ubuntu-20.04-java11
      script: |
        echo 3
    test-integration:
      machine: graknlabs-ubuntu-20.04-java11
      script: |
        echo 4
    test-behaviour:
      machine: graknlabs-ubuntu-20.04-java11
      script: |
        echo 5
    test-assembly-linux-targz:
      machine: graknlabs-ubuntu-20.04-java11
      filter:
        owner: graknlabs
        branch: master
      dependencies: [build, build-dependency, test-integration, test-behaviour]
      script: |
        echo 6
    test-assembly-docker:
      machine: graknlabs-ubuntu-20.04-java11
      filter:
        owner: graknlabs
        branch: master
      dependencies: [build, build-dependency, test-integration, test-behaviour]
      script: |
        echo 7
    deploy-artifact-snapshot:
      machine: graknlabs-ubuntu-20.04-java11
      filter:
        owner: graknlabs
        branch: master
      dependencies: [test-assembly-linux-targz]
      script: |
        echo 8
    deploy-apt-snapshot:
      machine: graknlabs-ubuntu-20.04-java11
      filter:
        owner: graknlabs
        branch: master
      dependencies: [test-assembly-linux-targz]
      script: |
        echo 9
    deploy-rpm-snapshot:
      machine: graknlabs-ubuntu-20.04-java11
      filter:
        owner: graknlabs
        branch: master
      dependencies: [test-assembly-linux-targz]
      script: |
        echo 10
    test-deployment-apt:
      machine: graknlabs-ubuntu-20.04-java11
      filter:
        owner: graknlabs
        branch: master
      dependencies: [deploy-apt-snapshot]
      script: |
        echo 11
    test-deployment-rpm:
      machine: graknlabs-centos-8.2
      filter:
        owner: graknlabs
        branch: master
      dependencies: [deploy-rpm-snapshot]
      script: |
        echo 12
release:
  filter:
    owner: graknlabs
    branch: master
  validation:
    validate-dependencies:
      machine: graknlabs-ubuntu-20.04-java11
      script: bazel test //:release-validate-deps --test_output=streamed
  deployment:
    deploy-github:
      machine: graknlabs-ubuntu-20.04-java11
      filter:
        owner: graknlabs
        branch: master
      script: |
        echo 13
    deploy-brew:
      machine: graknlabs-ubuntu-20.04-java11
      dependencies: [deploy-github]
      filter:
        owner: graknlabs
        branch: master
      script: |
        echo 14
    deploy-apt-release:
      machine: graknlabs-ubuntu-20.04-java11
      filter:
        owner: graknlabs
        branch: master
      dependencies: [deploy-github]
      script: |
        echo 15
    deploy-rpm-release:
      machine: graknlabs-ubuntu-20.04-java11
      filter:
        owner: graknlabs
        branch: master
      dependencies: [deploy-github]
      script: |
        echo 16
    deploy-docker:
      machine: graknlabs-ubuntu-20.04-java11
      filter:
        owner: graknlabs
        branch: master
      dependencies: [deploy-github]
      script: |
        echo 17
    deploy-artifact-release:
      machine: graknlabs-ubuntu-20.04-java11
      filter:
        owner: graknlabs
        branch: master
      dependencies: [deploy-github]
      script: |
        echo 18