config:
  version-candidate: VERSION
  dependencies:
    common: [snapshot]
build:
  quality:
      dependency-analysis:
        machine: graknlabs-ubuntu-20.04
        script: |
          echo $GRABL_URL
