#
# Copyright (C) 2020 Grakn Labs
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

config:
  version-candidate: VERSION

build:
  quality:
    filter:
      owner: graknlabs-test
      branch: main
    quality-1:
      filter:
        owner: graknlabs-test
        branch: main
      machine: graknlabs-ubuntu-20.04-java11
      script: |
        echo quality-1
    quality-2:
      filter:
        owner: graknlabs-test-123
        branch: main
      machine: graknlabs-ubuntu-20.04-java11
      script: |
        echo quality-2
    quality-3:
      filter:
        owner: graknlabs-test
        branch: main-123
      machine: graknlabs-ubuntu-20.04-java11
      script: |
        echo quality-3
  correctness:
    correctness-1-a:
      type: background
      machine: graknlabs-ubuntu-20.04-java11
      script: |
        echo correctness-1-a
    correctness-1-b:
      type: foreground
      machine: graknlabs-ubuntu-20.04-java11
      script: |
        echo correctness-1-b
    correctness-2:
      machine: graknlabs-ubuntu-20.04-java11
      dependencies: [correctness-1-a, correctness-1-b]
      script: |
        echo correctness-2
    correctness-3:
      machine: graknlabs-ubuntu-20.04-java11
      dependencies: [correctness-2]
      script: |
        echo correctness-3
  performance:
    performance-1:
      machine: graknlabs-ubuntu-20.04-java11
      script: |
        for VARIABLE in {1..1000}
        do
            echo 1 - 1000   -> $VARIABLE
        done
        for VARIABLE in {1..1000}
        do
            echo 1001 - 2000   -> $VARIABLE
        done
        for VARIABLE in {1..1000}
        do
            echo 2001 - 3000   -> $VARIABLE
        done
        for VARIABLE in {1..1000}
        do
            echo 3001 - 4000   -> $VARIABLE
        done
        for VARIABLE in {1..1000}
        do
            echo 4001 - 5000   -> $VARIABLE
        done
        for VARIABLE in {1..1000}
        do
            echo 5001 - 6000   -> $VARIABLE
        done
        for VARIABLE in {1..1000}
        do
            echo 6001 - 7000   -> $VARIABLE
        done
        for VARIABLE in {1..1000}
        do
            echo 7001 - 8000   -> $VARIABLE
        done
        for VARIABLE in {1..1000}
        do
            echo 8001 - 9000   -> $VARIABLE
        done
        for VARIABLE in {1..1000}
        do
            echo 9001 - 10000   -> $VARIABLE
        done
release:
  validation:
    validation-1:
      machine: graknlabs-ubuntu-20.04-java11
      script: |
        echo 12
  deployment:
    deployment-1:
      machine: graknlabs-ubuntu-20.04-java11
      script: |
        echo 13
    deployment-2:
      machine: graknlabs-ubuntu-20.04-java11
      dependencies: [deployment-1]
      script: |
        test
    deployment-3:
      machine: graknlabs-ubuntu-20.04-java11
      dependencies: [deployment-2]
      script: |
        test
  broadcast:
    broadcast-1:
      machine: graknlabs-ubuntu-20.04-java11
      type: foreground
      script: |
        test
