config:
  version-candidate: VERSION
build:
  quality:
      test-job:
        machine: graknlabs-ubuntu-20.04
        script: |
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
          echo 1
