config:
  version-candidate: VERSION
build:
  quality:
      test-job:
        machine: graknlabs-ubuntu-20.04
        script: |
          echo "$i iterations complete"
release: 
  deployment:
    job:
      machine: graknlabs-ubuntu-20.04
      script: |
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
        ECHO 1
